#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  sonar,               sensorSONAR_inch)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title: VEX Robotic
Team Members: Thien Tran, Kobe Chauvin
Date: 4-3-17
Section: The Banana


Task Description:


Pseudocode:

Get Sensor Value > If Above 700 Turn On Flashlight, If Below Turn Off
*/

task main()
{
while (true){
	if (SensorValue(lightsensor)>700) //Turn On Light When Light Sensor Value Is Above 700
	{
		turnFlashlightOn(flashlight, 127);
	}

	if (SensorValue(lightsensor)<=700) //Turn Off Light When Sensor Value Equal or Below 700
	{
	turnFlashLightOff(flashlight)
	}
	}
}
