#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  ,               sensorSONAR_inch)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title: VEX Robotic
Team Members: Thien Tran, Ryan Luong
Date: 3-21-17
Section: Yellow Ninjas


Task Description:


Pseudocode:
Go to position -127 > Wait 2 Seconds - Continue
Go to position -63 > Wait 3 seconds - Continue
Go to position 0 > Wait 2 Seconds - Continue
Go to position 63 > Wait 3 Seconds - Continue
Go to position 127 > Wait 2 Seconds - End

*/

task main()
{
	setServo(servoMotor, -127);
	wait(2)
	setServo(servoMotor, -63)
	wait(3)
	setServo(servoMotor, 0)
	wait(2)
	setServo(servoMotor, 63)
	wait(3)
	setServo(servoMotor, 127)
	wait(2)
}
